In [14]:
a= 17
b= 5 
a+b
a-b
a/b
a//b
a*b
a**b
print(a**b)
print("\n",type(a) , "\n" ,type(a/b))
print(f'a+b={a+b}')

1419857

 <class 'int'> 
 <class 'float'>
a+b=22


In [27]:
p=True 
q= False 
p and q
p or q 
not p 
not q
p != q 
print(not p)
score=30
if score>= 85:
   print("Distinction")
elif score >70<84:
    print("Merit")
elif score>50<69:
    print("Pass")
else:
    print("Fail")


False
Fail


In [31]:
sentence = "  Python is a powerful programming language  "
a=sentence.upper()
b=sentence.lower()
c=sentence.replace("powerful","versatile")
d=sentence.split()
e= sentence.strip()
f=sentence.count("a")
g=len(sentence)
h=sentence[:4]
print(f"The sentence has X words.{f}")


The sentence has X words.4


In [19]:

for i in range(31):
    if i % 2 == 0:
        print(i)   


j = 1
number = 0  

while j <= 100:
    if j % 2 == 0:        
        number = number + j 
    j += 1                   

print(f"The final sum of even numbers is: {number}")

for k in range(1,21):
    if k%2==1 and k%5==0:
       print("fizbuz")
    elif k%2==1:
         print("Fizz")
    elif k%5==0:
         print("Bizz")

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
The final sum of even numbers is: 2550
Fizz
Fizz
fizbuz
Fizz
Fizz
Bizz
Fizz
Fizz
fizbuz
Fizz
Fizz
Bizz


In [41]:
fruits = ["mango", "banana", "apple", "cherry", "orange"]
print(fruits[0],"\n",fruits[-2])
fruits.append("grape")
print(fruits)
fruits.insert(2,"kiwi")
print(fruits)
fruits.remove("banana")
print(fruits)
fruits.pop(0)
print(fruits,"is remove")
fruits.sort()
print(fruits)
fruits.reverse()
print(fruits)



mango 
 cherry
['mango', 'banana', 'apple', 'cherry', 'orange', 'grape']
['mango', 'banana', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
['mango', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
['kiwi', 'apple', 'cherry', 'orange', 'grape'] is remove
['apple', 'cherry', 'grape', 'kiwi', 'orange']
['orange', 'kiwi', 'grape', 'cherry', 'apple']


In [57]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers[0:4])
print(numbers[-1:-4:-1])
print(numbers[2:7])
print(numbers[::2])
print(numbers[::-1])
print(numbers[-1:-6:-1])

[0, 1, 2, 3]
[9, 8, 7]
[2, 3, 4, 5, 6]
[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9, 8, 7, 6, 5]


In [8]:
data = list(range(16))
print(data)
square = [i**2 for i in data ]
print(square)
number=list(range(51))
print(number)
divisible=[ i for i in number if i%3==0 or i%5==0]
print(divisible)
sentence="the quick brown fox jumps over the lazy dog"
function=sentence.split()
lenght=[len(i) for i in sentence.split() ]
print(lenght)
uppercase =['QUICK', 'BROWN', 'JUMPS', 'LAZY']
version=[i for i in uppercase if len(i)>=5]
print(version)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50]
[3, 5, 5, 3, 5, 4, 3, 4, 3]
['QUICK', 'BROWN', 'JUMPS']


In [39]:
import numpy as np
import random 
from collections import Counter
matrix=[[i for i in range(1,4)] ,
        [j for j in range(4,7)],
        [k for k in range(7,10)]]
print(matrix)
print(matrix[1])
print(matrix[1][0])
m1=np.array(matrix)
print(m1.T)
list=[random.randint(1,10) for _ in range(300)]
print(list)
print(Counter(list)) 
print(Counter(list).most_common(3))
print(Counter(list).most_common()[-3:])



[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[4, 5, 6]
4
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[3, 4, 2, 3, 8, 3, 7, 8, 4, 8, 7, 5, 2, 4, 8, 5, 6, 10, 8, 8, 8, 1, 2, 3, 4, 9, 2, 5, 9, 2, 10, 6, 1, 4, 4, 6, 1, 3, 1, 7, 8, 6, 1, 10, 5, 6, 8, 4, 2, 2, 5, 10, 9, 1, 8, 6, 8, 5, 7, 9, 1, 7, 10, 7, 9, 1, 7, 2, 8, 1, 9, 1, 9, 3, 5, 9, 2, 3, 5, 3, 4, 8, 5, 5, 4, 5, 1, 5, 8, 10, 9, 8, 9, 1, 5, 5, 5, 2, 3, 3, 5, 3, 10, 9, 1, 5, 5, 8, 5, 7, 4, 10, 2, 10, 5, 2, 1, 1, 10, 7, 1, 2, 9, 4, 8, 1, 1, 10, 5, 5, 1, 1, 4, 5, 5, 7, 10, 2, 4, 10, 9, 2, 1, 4, 8, 2, 8, 8, 7, 8, 10, 8, 10, 6, 7, 5, 4, 10, 2, 9, 10, 9, 6, 3, 7, 6, 9, 2, 8, 10, 9, 4, 2, 1, 9, 1, 6, 7, 10, 1, 1, 10, 6, 10, 3, 2, 9, 2, 2, 4, 8, 7, 9, 6, 5, 3, 9, 10, 2, 4, 6, 5, 8, 8, 6, 7, 9, 9, 1, 3, 1, 9, 9, 9, 9, 1, 6, 5, 1, 4, 8, 5, 7, 9, 4, 8, 3, 8, 1, 5, 7, 6, 10, 9, 4, 3, 3, 4, 10, 4, 2, 8, 2, 1, 1, 6, 7, 1, 3, 9, 9, 2, 8, 3, 7, 7, 5, 6, 3, 1, 7, 9, 7, 7, 9, 1, 6, 2, 2, 4, 6, 5, 10, 3, 2, 1, 8, 7, 7, 10, 5, 3, 1, 4, 1, 2, 8, 10, 3, 6, 6, 6, 10, 9, 6, 9, 7, 1, 3, 

In [61]:
student = ("Alice", 22, "Computer Science", 3.8)
print(student[0],student[3])
try:
  student[0]='bob'
except:
    print('tuples are immutable')
name, _,_, gpa=student
print(gpa)
cities = [("Karachi", 24.86, 67.01),
          ("Lahore",  31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar", 34.01, 71.57),
          ("Quetta",  30.18, 66.99)]
for i in cities:
    print("City:",i[0] , "Lat:", i[1] , "Lon:" ,i[2])
sorted_by_lat = sorted(cities, key=lambda i: i[1])

for city_folder in sorted_by_lat:
    print(city_folder)
    

Alice 3.8
tuples are immutable
3.8
City: Karachi Lat: 24.86 Lon: 67.01
City: Lahore Lat: 31.55 Lon: 74.35
City: Islamabad Lat: 33.72 Lon: 73.06
City: Peshawar Lat: 34.01 Lon: 71.57
City: Quetta Lat: 30.18 Lon: 66.99
('Karachi', 24.86, 67.01)
('Quetta', 30.18, 66.99)
('Lahore', 31.55, 74.35)
('Islamabad', 33.72, 73.06)
('Peshawar', 34.01, 71.57)


In [48]:
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}
print(student["grades"])
print(student.get("name"))
print(student["grades"]["CS"])
student['year']=2
print(student)
print(student.update({"age":21}))
print(student)
#student["grades"]["CS"]=98
print(student["grades"].update({"CS":97}))
print(student)
print(student["grades"].pop("Physics"))
print(student)
for i in student.items():
    print(i)
print(student.keys())
print(student.values())


{'Math': 88, 'Physics': 75, 'CS': 92}
Sara
92
{'name': 'Sara', 'age': 20, 'courses': ['Math', 'Physics', 'CS'], 'grades': {'Math': 88, 'Physics': 75, 'CS': 92}, 'year': 2}
None
{'name': 'Sara', 'age': 21, 'courses': ['Math', 'Physics', 'CS'], 'grades': {'Math': 88, 'Physics': 75, 'CS': 92}, 'year': 2}
None
{'name': 'Sara', 'age': 21, 'courses': ['Math', 'Physics', 'CS'], 'grades': {'Math': 88, 'Physics': 75, 'CS': 97}, 'year': 2}
75
{'name': 'Sara', 'age': 21, 'courses': ['Math', 'Physics', 'CS'], 'grades': {'Math': 88, 'CS': 97}, 'year': 2}
('name', 'Sara')
('age', 21)
('courses', ['Math', 'Physics', 'CS'])
('grades', {'Math': 88, 'CS': 97})
('year', 2)
dict_keys(['name', 'age', 'courses', 'grades', 'year'])
dict_values(['Sara', 21, ['Math', 'Physics', 'CS'], {'Math': 88, 'CS': 97}, 2])


In [10]:
from collections import Counter
cube={i:i**3 for i in range(11)}
print(cube)
number={i:"even" if i%2==0  else "odd" for i in range(1,21) }
print(number)
text = "to be or not to be that is the question to be is to think"

#p=text.count("to")
#word_count={i:text.count(i) for i in text.lower().split()} it have bug "tomato" and to frequency to=2
#words_count= Counter(text.lower().split())  
#print(words_count.most_common()[::-1])
freq = {}
for word in text.lower().split():
    freq[word] = freq.get(word, 0) + 1
sorted_list = sorted(freq.items(), key=lambda x: x[1], reverse=True)
for word, count in sorted_list:
    print(f"{word}: {count}")
    



{0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}
{1: 'odd', 2: 'even', 3: 'odd', 4: 'even', 5: 'odd', 6: 'even', 7: 'odd', 8: 'even', 9: 'odd', 10: 'even', 11: 'odd', 12: 'even', 13: 'odd', 14: 'even', 15: 'odd', 16: 'even', 17: 'odd', 18: 'even', 19: 'odd', 20: 'even'}
to: 4
be: 3
is: 2
or: 1
not: 1
that: 1
the: 1
question: 1
think: 1


In [39]:
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}
print(python_students&java_students)
print(python_students|java_students)
print(python_students-java_students)
print(python_students^java_students)
#python_students.remove( "Carol")
python_students.discard("Carol")
#python_students.add("Henry")
python_students.update(["Henry"])
print(python_students)
lis=[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
#print(set(lis))
print(list(dict.fromkeys(lis)))


{'Alice', 'Bob', 'David'}
{'Eve', 'Carol', 'David', 'Grace', 'Alice', 'Bob', 'Frank'}
{'Eve', 'Carol'}
{'Eve', 'Carol', 'Grace', 'Frank'}
{'Eve', 'David', 'Alice', 'Bob', 'Henry'}
[1, 2, 3, 4]


In [60]:
import numpy as np
a=np.arange(0,21,2)
print(a)
print(type(a))
print(a.shape)
b=np.linspace(0,1,6)
print(b,"\n",type(b),"\n",b.shape)
c=np.zeros((3 , 4))
print(c)
d=np.ones((2,5))
print(d)
e=np.eye(4,2)
print(e)
f=np.random.randint(1, 100, size=(3, 3))
print(f)



[ 0  2  4  6  8 10 12 14 16 18 20]
<class 'numpy.ndarray'>
(11,)
[0.  0.2 0.4 0.6 0.8 1. ] 
 <class 'numpy.ndarray'> 
 (6,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]
[[37 95 42]
 [83 23 53]
 [15 96 93]]


In [47]:
import numpy as np
A = np.arange(1,26).reshape(5,5)
print(A)
print(A[2][3])
print()
print(A[2])
print()
print(A[:,1])
print()
print(A[0:3,0:3])
print()
#print(A[-2:,-2:])
print(A[3:5,3:5])
print()
print(A.T)
column_vector = A.reshape(25, 1)
print(column_vector)
print(A.flatten()) #.flatten(): This creates a 1D Array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
14

[11 12 13 14 15]

[ 2  7 12 17 22]

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]

[[19 20]
 [24 25]]

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [74]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
square_root=np.sqrt(a)
print(square_root)
'''for i in a:
   if i>25:
     print(f'true:{i}')'''
print(a>25)
mask=a<25
print(a[mask])# [] to extract mask values according to the condition
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
print()
print(M*N)
print()
print(M@N)
print()
print(M.sum(axis=0))#0 for row and 1 for columns (axis is paramater which add all row and columns according to its value)


[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[False False  True  True  True]
[10 20]

[[ 5 12]
 [21 32]]

[[19 22]
 [43 50]]

[4 6]


In [106]:
import pandas as pd 
data = {
    "Name":    ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":     [23, 21, 25, 22, 24],
    "Score":   [88, 92, 78, 95, 83],
    "Passed":  [True, True, True, True, True],
    "City":    ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}
a=pd.DataFrame(data)
print(a)
print(a.shape)
print(a.columns)
print(a.iloc[0:2])#You don't know the names of the columns You want to grab a specific "chunk" of the table
print(a.head(1))
print(a.tail(1))
print(a.dtypes)
print()
print(a['Age'].dtypes)# to find the datatype of a specific column 
print(a.info())


     Name  Age  Score  Passed       City
0     Ali   23     88    True     Lahore
1    Sara   21     92    True    Karachi
2    John   25     78    True     London
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York
(5, 5)
Index(['Name', 'Age', 'Score', 'Passed', 'City'], dtype='object')
   Name  Age  Score  Passed     City
0   Ali   23     88    True   Lahore
1  Sara   21     92    True  Karachi
  Name  Age  Score  Passed    City
0  Ali   23     88    True  Lahore
    Name  Age  Score  Passed      City
4  Chris   24     83    True  New York
Name      object
Age        int64
Score      int64
Passed      bool
City      object
dtype: object

int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   Score   5 non-null      int64 
 3   Passed  5 non-null      bool  
